name: ENV demo
on:
    workflow_dispatch:
env:
    APP_ENV: production
jobs:
    env-demo:
        runs-on: ubuntu-latest
        JOB_PART: production
        steps:
            - name: connect to env
              run: |
                echo  "App is connecting to $APP_ENV "
                echo  "App is connecting to $JOB_PART "