name: Inputs demo
on: 
  workflow_dispatch:
    inputs:
      enviroment:
        description: choose env to deploy
        required: true
        default: development
jobs:
  inputs-demo:
    runs-on: ubuntu-24.04
    steps:
      - name: deploy the app
        run: |
          echo " deploy application to ${{inputs.enviroment}}"
