git clone your git hub file https
git config --global user.email "ldlq2005@gmail.com"
git config --global user.name "quanldl"
git commit -am "push trigger"
git push origin main
git pull origin main --rebase

----
cd terraform-folder
git init
git remote add origin https://github.com/yourname/my-app-infra.git
git add .
git commit -m "Initial infra"
git push -u origin main