name: hello world
on: push
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo " welcome to ${{ vars.MY_NAME }}"
  goodbye:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Hello Step
        run: |
          echo " say goodbye to ghaction"
          
        
