name: hello world

on:
  workflow_dispatch:

jobs:
  whats-up:
    runs-on: ubuntu-24.04
    steps:
      - name: run command hello world
        id: id-foo
        run: |
          hello-world=foo
          echo "foobar=${hello-world}" >> GITHUB_OUTPUT
          echo "foo=${hello-world}" >> GITHUB_ENV
      - name: hi
        run: |
          echo "foo (ENV): $foo"
          echo "foobar (OUTPUT): ${steps.id-foo.outputs.foobar} "
          
          
          
          
