name: Call Workflow from reusable workflow
on:
    push:
jobs:
    call-greeting:
        uses: ./.github/workflows/reusable-workflow.yaml
        with: 
            version: 0.5.3
  
        
        