name: context variables
on: 
  push:
jobs:
  context-demo:
    runs-on: ubuntu-24.04
    steps:
      - name: Use context variable
        run: |
            echo "This workflow is triggered by ${{ github.actor }} "
            echo "The repository is ${{ github.repository }}"
            
      