name: git-action
on: push
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: print index.html
        run: cat my-github-action-demo\index.html

      - name: Hello Step
        run: |
          echo " welcome to ${{ vars.MY_NAME }}"
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo " say goodbye to ${{secrets.DOCKER_PASSWORD}}"
          
        
