name: If Condition/feature/demo

on:
  push:
    branches:
        - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Build Step
        run: echo "running this step as the notification"
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.ref_name == 'main'
    steps:
      - name: Build Step
        run: echo "running this step as the notification"
