name: If Condition/feature/demo

on:
  push:
    
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "running this step as the notification"