name: Nice if example
on:
    push:
        branches:
            - main 
            - development
            - feature/**
jobs:
    quality-check:
        runs-on: ubuntu-latest
        if: startsWith(github.ref_name,'feature/') && github.event_name == 'push'
        steps:
            - name: perform code quality
              run: echo "performing quality checks on the code "
    dev-deploy:
        runs-on: ubuntu-latest
        if: startsWith(github.ref_name,'develop') && github.event_name == 'push'
        steps:
            - name: perform code quality
              run: echo "deploying the code to ${{github.ref_name}}"
    prod-deploy:
        runs-on: ubuntu-latest
        if: startsWith(github.ref_name,'main') && github.event_name == 'push'
        steps:
            - name: perform code quality
              run: echo "deploying the code to ${{github.ref_name}}" 
    successful-notification:
        runs-on: ubuntu-latest
        if: always() && !failure()
        needs:
            - quality-check
            - dev-deploy
            - prod-deploy
        steps:
            - name: successfull notification
           
              run: echo "email is working" 
           
    failed-notification:
        runs-on: ubuntu-latest
        if: always() && failure()
        needs:
            - quality-check
            - dev-deploy
            - prod-deploy
        steps:
          
            - name:  failed notification
          
              run: echo "email is  failed to send"

    