name: Reusable Workflow
on:
    workflow_call:
        inputs:
            version:
                description: enter the name
                required: true
                type: 'string'
jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting
              run: |
                echo "Welcome to reusable workflow with the version ${{inputs.version}}"
  
        
        