name: secret-and-vars
on: workflow_dispatch
env:
    APP_ENV: production
    
jobs:
  hello:
    env:
      APP_ENV: production
      JOB_PART: production
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo " welcome to ${{ vars.MY_NAME }}"
  goodbye:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Hello Step
        run: |
          echo " say goodbye to ${{secrets.DOCKER_PASSWORD}}"
  env-demo:
    runs-on: ubuntu-latest
    env:
        APP_ENV: production
    steps: 
        - name: connect to env
          run: |
            echo  "App is connecting to $APP_ENV "
            echo  "App is connecting to $JOB_PART "
          
        
